name: Rcaas Api Pipeline
on:
  push:
    branches: [ "master" ]
    paths:
      - rcaas-api/**
  workflow_dispatch:
env:
  APP_NAME: rcaas-api
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build docker image
        run: docker build $APP_NAME --file $APP_NAME/Dockerfile --tag ${{ secrets.DOCKER_REGISTRY }}/$APP_NAME
      - name: Docker login
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker push
        run: docker push ${{ secrets.DOCKER_REGISTRY }}/$APP_NAME
