name: Rcaas Api Pipeline
on:
  push:
    branches: [ "master" ]
    paths:
      - rcaas-api/**
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image
        run: docker build rcaas-api --file rcaas-api/Dockerfile --tag ${{ secrets.DOCKER_REGISTRY }}/rcaas-api
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Docker Push Image
        run: docker push ${{ secrets.DOCKER_REGISTRY }}/rcaas-api
  deploy:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy container with new image version
        run: |
          curl \
          --request POST \
          --header "X-Auth-Token: ${{ secrets.DOCKER_TOKEN }}" \
          "https://api.scaleway.com/containers/v1beta1/regions/nl-ams/containers/29a7fd74-c1d8-4290-a7f7-01554bee7cf7/deploy" \
          -d "{}"
