name: Build UI
on:
  push:
    branches: [ "master" ]
    paths:
      - rcaas-ui/**
  workflow_dispatch:
env:
  APP_NAME: rcaas-ui
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker buildx build $APP_NAME --platform linux/arm64 --file $APP_NAME/Dockerfile --tag ${{ secrets.DOCKER_REGISTRY }}/$APP_NAME --push
