name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Rcaas Api Docker image
      run: docker build rcaas-api --file rcaas-api/Dockerfile --tag rg.nl-ams.scw.cloud/rcaas/rcaas-api
    - name: Build the Rcaas UI Docker image
      run: docker build rcaas-ui --file rcaas-ui/Dockerfile --tag rg.nl-ams.scw.cloud/rcaas/rcaas-ui
    - name: Docker Login
      uses: docker/login-action@v2
      with:
        registry: rg.nl-ams.scw.cloud/rcaas
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Push Docker images
      uses: docker/build-push-action@v4.0.0
      with:
        push: true
        tags: rg.nl-ams.scw.cloud/rcaas/rcaas-api rg.nl-ams.scw.cloud/rcaas/rcaas-ui
